Traceback (most recent call last):
  File "./learning/test.py", line 85, in <module>
    test(args)
  File "./learning/test.py", line 43, in test
    out = model(code, test, "", phase=2)
  File "/u/kl5sq/.conda/envs/seer/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/u/kl5sq/masters/SEER/models/joint_embedder.py", line 67, in forward
    code_repr = self.code_encoding(code)
  File "/u/kl5sq/masters/SEER/models/joint_embedder.py", line 35, in code_encoding
    code_repr = self.encoder(code)
  File "/u/kl5sq/.conda/envs/seer/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/u/kl5sq/masters/SEER/learning/modules.py", line 43, in forward
    src = self.encoder(src)
  File "/u/kl5sq/.conda/envs/seer/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/u/kl5sq/.conda/envs/seer/lib/python3.6/site-packages/torch/nn/modules/sparse.py", line 160, in forward
    self.norm_type, self.scale_grad_by_freq, self.sparse)
  File "/u/kl5sq/.conda/envs/seer/lib/python3.6/site-packages/torch/nn/functional.py", line 2044, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
IndexError: index out of range in self
Closing remaining open files:real_data_gen/fold0/label_test.h5...donereal_data_gen/fold0/test_test.h5...donereal_data_gen/fold0/code_test.h5...done
